de_properties_map = {
    'http://de.dbpedia.org/property/zeitzone': 'http://dbpedia.org/property/timezone',
    'http://de.dbpedia.org/property/vater': 'http://dbpedia.org/property/father',
    'http://de.dbpedia.org/property/spitzname': 'http://dbpedia.org/property/nickname',
    'http://de.dbpedia.org/property/künstler': 'http://dbpedia.org/property/artist',
    'http://de.dbpedia.org/property/zeichner': 'http://dbpedia.org/property/portrayer',
    'http://de.dbpedia.org/property/land': 'http://dbpedia.org/property/country',
    'http://de.dbpedia.org/property/mündung': 'http://dbpedia.org/property/mouthLocation',
    'http://de.dbpedia.org/property/standOrt': 'http://dbpedia.org/property/location',
    'http://de.dbpedia.org/property/geburtsort': 'http://dbpedia.org/ontology/birthPlace',
    'http://de.dbpedia.org/property/geburtsjahr': 'http://dbpedia.org/ontology/birthYear',
    'http://de.dbpedia.org/property/museum': 'http://dbpedia.org/ontology/museum',
    'http://de.dbpedia.org/property/produkt': 'http://dbpedia.org/ontology/product',
    'http://de.dbpedia.org/property/vizepräsident': 'http://dbpedia.org/ontology/vicePresident',
    'http://de.dbpedia.org/property/entdecker': 'http://dbpedia.org/ontology/discoverer',
    'http://dbpedia.org/ontology/discoverer': 'http://dbpedia.org/ontology/parent',
    'http://de.dbpedia.org/property/universität': 'http://dbpedia.org/ontology/almaMater',
    'http://de.dbpedia.org/property/bürgermeister': 'http://dbpedia.org/ontology/mayor',
    'http://de.dbpedia.org/property/bestandteile': 'http://dbpedia.org/ontology/ingredient',
    'http://de.dbpedia.org/property/moderator': 'http://dbpedia.org/ontology/presenter',
    'http://de.dbpedia.org/property/bedeutung': 'http://dbpedia.org/ontology/connotation',
    'http://de.dbpedia.org/property/gegründetVon': 'http://dbpedia.org/ontology/foundedBy',
    'http://de.dbpedia.org/property/komponist': 'http://dbpedia.org/ontology/composer',
    'http://de.dbpedia.org/property/datum': 'http://dbpedia.org/property/date',
    'http://de.dbpedia.org/property/ehemann': 'http://dbpedia.org/ontology/spouse',
    'http://de.dbpedia.org/property/partei': 'http://dbpedia.org/ontology/party',
    'http://de.dbpedia.org/property/ersteller': 'http://dbpedia.org/ontology/creator',
    'http://de.dbpedia.org/property/haushalt': 'http://dbpedia.org/ontology/budget',
    'http://de.dbpedia.org/property/wohnort': 'http://dbpedia.org/ontology/residence',
    'http://de.dbpedia.org/property/wohnsitz': 'http://dbpedia.org/ontology/residence',

}
