qald7_mappings = {'http://dbpedia.org/ontology/presenter': ['http://dbpedia.org/ontology/TelevisionShow',
                                                            'http://dbpedia.org/ontology/Person', ],
                  'http://dbpedia.org/ontology/creator': ['http://dbpedia.org/ontology/TelevisionShow',
                                                          'http://dbpedia.org/ontology/Person', ],
                  'http://dbpedia.org/ontology/product': ['http://dbpedia.org/ontology/Company',
                                                          'http://dbpedia.org/ontology/Software', ],
                  'http://dbpedia.org/ontology/musicComposer': ['http://dbpedia.org/ontology/Film',
                                                                'http://dbpedia.org/ontology/Person', ],
                  'http://dbpedia.org/property/artist': ['http://dbpedia.org/ontology/Work',
                                                         'http://dbpedia.org/ontology/Person', ],
                  'http://dbpedia.org/ontology/publisher': ['http://dbpedia.org/ontology/Work',
                                                            'http://dbpedia.org/ontology/Person', ],
                  'http://dbpedia.org/ontology/crosses': ['http://dbpedia.org/ontology/Bridge',
                                                          'http://dbpedia.org/ontology/River', ],
                  'http://dbpedia.org/ontology/award': ['http://dbpedia.org/ontology/Scientist',
                                                        'http://dbpedia.org/ontology/Award', ],
                  'http://dbpedia.org/ontology/budget': ['http://dbpedia.org/ontology/Film', 'xsd:double', ],
                  'http://dbpedia.org/ontology/writer': ['http://dbpedia.org/ontology/Song',
                                                         'http://dbpedia.org/ontology/Person', ],
                  'http://dbpedia.org/ontology/composer': ['http://dbpedia.org/ontology/TelevisionShow',
                                                           'http://dbpedia.org/ontology/Person', ],
                  'http://dbpedia.org/ontology/author': ['http://dbpedia.org/ontology/Book',
                                                         'http://dbpedia.org/ontology/Person', ],
                  'http://dbpedia.org/ontology/almaMater': ['http://dbpedia.org/ontology/Person',
                                                            'http://dbpedia.org/ontology/University', ],
                  'http://dbpedia.org/ontology/operator': ['http://dbpedia.org/ontology/Company',
                                                           'http://dbpedia.org/ontology/LaunchPad', ],
                  'http://dbpedia.org/ontology/foundedBy': ['http://dbpedia.org/ontology/Company',
                                                            'http://dbpedia.org/ontology/Pope', ],
                  'http://dbpedia.org/ontology/founder': ['http://dbpedia.org/ontology/Publisher',
                                                          'http://dbpedia.org/ontology/Person', ],
                  'http://dbpedia.org/ontology/firstAscentPerson': ['http://dbpedia.org/ontology/Mountain',
                                                                    'http://dbpedia.org/ontology/Person', ],
                  'http://dbpedia.org/ontology/discoverer': ['http://dbpedia.org/ontology/CelestialBody',
                                                             'http://dbpedia.org/ontology/Person', ],
                  'http://dbpedia.org/property/portrayer': ['http://dbpedia.org/ontology/FictionalCharacter',
                                                            'http://dbpedia.org/ontology/Person', ],
                  'http://dbpedia.org/ontology/director': ['http://dbpedia.org/ontology/Film',
                                                           'http://dbpedia.org/ontology/Person', ],
                  'http://dbpedia.org/ontology/influencedBy': ['http://dbpedia.org/ontology/Person',
                                                               'http://dbpedia.org/ontology/Person', ],
                  'http://dbpedia.org/ontology/influenced': ['http://dbpedia.org/ontology/Artist',
                                                             'http://dbpedia.org/ontology/Artist', ],
                  'http://dbpedia.org/ontology/architect': ['http://dbpedia.org/ontology/Bridge',
                                                            'http://dbpedia.org/ontology/Person', ],
                  'http://dbpedia.org/ontology/spouse': ['http://dbpedia.org/ontology/Person',
                                                         'http://dbpedia.org/ontology/Person', ],
                  'http://dbpedia.org/ontology/routeEnd': ['http://dbpedia.org/ontology/Road',
                                                           'http://dbpedia.org/ontology/Location', ],
                  'http://dbpedia.org/ontology/deathCause': ['http://dbpedia.org/ontology/Person',
                                                             'http://dbpedia.org/ontology/Disease', ],
                  'http://dbpedia.org/ontology/deathDate': ['http://dbpedia.org/ontology/Person', 'xsd:date', ],
                  'http://dbpedia.org/ontology/deathPlace': ['http://dbpedia.org/ontology/Person',
                                                             'http://dbpedia.org/ontology/City', ],
                  'http://dbpedia.org/ontology/city': ['http://dbpedia.org/ontology/River',
                                                       'http://dbpedia.org/ontology/City', ],
                  'http://dbpedia.org/property/country': ['http://dbpedia.org/ontology/River',
                                                          'http://dbpedia.org/ontology/Country', ],
                  'http://dbpedia.org/ontology/routeStart': ['http://dbpedia.org/ontology/Place',
                                                             'http://dbpedia.org/ontology/Road', ],
                  'http://dbpedia.org/ontology/language': ['http://dbpedia.org/ontology/Country',
                                                           'http://dbpedia.org/ontology/Language', ],
                  'http://dbpedia.org/property/mouthLocation': ['http://dbpedia.org/ontology/River',
                                                                'http://dbpedia.org/ontology/Place', ],
                  'http://dbpedia.org/ontology/birthYear': ['http://dbpedia.org/ontology/Person', 'xsd:date', ],
                  'http://dbpedia.org/ontology/birthPlace': ['http://dbpedia.org/ontology/Person',
                                                             'http://dbpedia.org/ontology/Place', ],
                  'http://dbpedia.org/ontology/completionDate': ['http://dbpedia.org/ontology/Ship', 'xsd:date', ],
                  'http://dbpedia.org/ontology/museum': ['http://dbpedia.org/ontology/Artwork',
                                                         'http://dbpedia.org/ontology/Museum', ],
                  'http://dbpedia.org/ontology/country': ['http://dbpedia.org/ontology/Lake',
                                                          'http://dbpedia.org/ontology/Country', ],
                  'http://dbpedia.org/ontology/programmingLanguage': ['http://dbpedia.org/ontology/Software',
                                                                      'http://dbpedia.org/ontology/Language', ],
                  'http://dbpedia.org/ontology/residence': ['http://dbpedia.org/ontology/Person',
                                                            'http://dbpedia.org/ontology/City', ],
                  'http://dbpedia.org/ontology/dissolutionDate': ['http://dbpedia.org/ontology/Country', 'xsd:date', ],
                  'http://dbpedia.org/property/location': ['http://dbpedia.org/ontology/MilitaryUnit',
                                                           'http://dbpedia.org/ontology/Location', ],
                  'http://dbpedia.org/ontology/locatedInArea': ['http://dbpedia.org/ontology/Mountain',
                                                                'http://dbpedia.org/ontology/Country', ],
                  'http://dbpedia.org/ontology/abbreviation': ['owl:Thing', 'xsd:string'],
                  'http://dbpedia.org/ontology/connotation': ['http://dbpedia.org/ontology/Colour', 'owl:Thing', ],
                  'http://dbpedia.org/ontology/populationTotal': ['http://dbpedia.org/ontology/Country',
                                                                  'xsd:double', ],
                  'http://dbpedia.org/ontology/growingGrape': ['http://dbpedia.org/ontology/WineRegion',
                                                               'http://dbpedia.org/ontology/Grape', ],
                  'http://dbpedia.org/ontology/wineRegion': ['http://dbpedia.org/ontology/Grape',
                                                             'http://dbpedia.org/ontology/WineRegion', ],
                  'http://dbpedia.org/ontology/starring': ['http://dbpedia.org/ontology/Film',
                                                           'http://dbpedia.org/ontology/Person', ],
                  'http://dbpedia.org/property/nickname': ['http://dbpedia.org/ontology/Person', 'xsd:string', ],
                  'http://dbpedia.org/ontology/capital': ['http://dbpedia.org/ontology/Country',
                                                          'http://dbpedia.org/ontology/City', ],
                  'http://dbpedia.org/ontology/mayor': ['http://dbpedia.org/ontology/City',
                                                        'http://dbpedia.org/ontology/Person', ],
                  'http://dbpedia.org/ontology/leaderName': ['http://dbpedia.org/ontology/City',
                                                             'http://dbpedia.org/ontology/Person', ],
                  'http://dbpedia.org/ontology/height': ['http://dbpedia.org/ontology/Lighthouse', 'xsd:integer', ],
                  'http://dbpedia.org/ontology/officialLanguage': ['http://dbpedia.org/ontology/Country',
                                                                   'http://dbpedia.org/ontology/Language', ],
                  'http://dbpedia.org/ontology/editor': ['http://dbpedia.org/ontology/WrittenWork',
                                                         'http://dbpedia.org/ontology/Person', ],
                  'http://dbpedia.org/ontology/child': ['http://dbpedia.org/ontology/Person',
                                                        'http://dbpedia.org/ontology/Person', ],
                  'http://dbpedia.org/ontology/bandMember': ['http://dbpedia.org/ontology/Band',
                                                             'http://dbpedia.org/ontology/Person', ],
                  'http://dbpedia.org/ontology/coach': ['http://dbpedia.org/ontology/IceHockeyLeague',
                                                        'http://dbpedia.org/ontology/CollegeCoach', ],
                  'http://dbpedia.org/ontology/musicBy': ['http://dbpedia.org/ontology/Musical',
                                                          'http://dbpedia.org/ontology/Person', ],
                  'http://dbpedia.org/ontology/governmentType': ['http://dbpedia.org/ontology/Country',
                                                                 'http://dbpedia.org/ontology/GovernmentType', ],
                  'http://dbpedia.org/ontology/developer': ['http://dbpedia.org/ontology/Software',
                                                            'http://dbpedia.org/ontology/University', ],
                  'http://dbpedia.org/ontology/areaCode': ['http://dbpedia.org/ontology/Place', 'xsd:string', ],
                  'http://dbpedia.org/ontology/vicePresident': ['http://dbpedia.org/ontology/Person',
                                                                'http://dbpedia.org/ontology/Country', ],
                  'http://dbpedia.org/ontology/successor': ['http://dbpedia.org/ontology/Politician',
                                                            'http://dbpedia.org/ontology/Person', ],
                  'http://dbpedia.org/ontology/currency': ['http://dbpedia.org/ontology/Country',
                                                           'http://dbpedia.org/ontology/Currency', ],
                  'http://dbpedia.org/ontology/doctoralAdvisor': ['http://dbpedia.org/ontology/Person',
                                                                  'http://dbpedia.org/ontology/Person', ],
                  'http://dbpedia.org/ontology/parent': ['http://dbpedia.org/ontology/Person',
                                                         'http://dbpedia.org/ontology/Person', ],
                  'http://dbpedia.org/ontology/largestCity': ['http://dbpedia.org/ontology/Country',
                                                              'http://dbpedia.org/ontology/City', ],
                  'http://dbpedia.org/property/alterEgo': ['http://dbpedia.org/ontology/FictionalCharacter',
                                                           'xsd:string', ],
                  'http://dbpedia.org/ontology/leader': ['http://dbpedia.org/ontology/Legislature',
                                                         'http://dbpedia.org/ontology/Person', ],
                  'http://dbpedia.org/ontology/timeZone': ['http://dbpedia.org/ontology/Town', 'xsd:string', ],
                  'http://dbpedia.org/property/timezone': ['http://dbpedia.org/ontology/City', 'xsd:string', ],
                  'http://dbpedia.org/property/father': ['http://dbpedia.org/ontology/Person',
                                                         'http://dbpedia.org/ontology/Person', ],
                  'http://dbpedia.org/ontology/ingredient': ['http://dbpedia.org/ontology/Food', 'owl:Thing', ],
                  'http://dbpedia.org/ontology/nationality': ['http://dbpedia.org/ontology/Person',
                                                              'http://dbpedia.org/ontology/Country', ],
                  'http://dbpedia.org/ontology/party': ['http://dbpedia.org/ontology/Politician', 'xsd:string', ],
                  'http://dbpedia.org/ontology/ground': ['http://dbpedia.org/ontology/SportsClub',
                                                         'http://dbpedia.org/ontology/Stadium', ], }
